Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,3 +7,12 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     - run: python3 /home/hungry.cho/test.py
+    - name: Check the result
+      run: |
+        if [ "$(python3 /home/hungry.cho/test.py)" = "hello world" ]; then
+          echo "Test Passed!"
+          exit 0
+        else
+          echo "Test failed"
+          exit 1
+        fi
